name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'src'
          filename: '${{ github.event.repository.name }}-${{  github.ref_name }}.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig .vscode .vscode/* README.md tooltip.png'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          name: 'v${{  github.ref_name }}'
          artifacts: "src/${{ github.event.repository.name }}-${{  github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
